import {
  Users,
  CalendarDays,
  ClipboardList,
  CreditCard,
  UserRoundCog,
  Images,
  Activity,
} from "@lucide/vue";

export const reportTypes = [
  {
    id: "members",
    title: "Member Report",
    description: "View member statistics, growth and account status.",
    icon: Users,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-400",
    route: "/dashboard/reports/members",
  },
  {
    id: "events",
    title: "Event Report",
    description: "Analyze events, status, schedule and activities.",
    icon: CalendarDays,
    iconBg: "bg-cyan-500/10",
    iconColor: "text-cyan-400",
    route: "/dashboard/reports/events",
  },
  {
    id: "registrations",
    title: "Registration Report",
    description: "Track event registrations and participation.",
    icon: ClipboardList,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-400",
    route: "/dashboard/reports/registrations",
  },
  {
    id: "payments",
    title: "Payment Report",
    description: "Monitor event payments and transactions.",
    icon: CreditCard,
    iconBg: "bg-yellow-500/10",
    iconColor: "text-yellow-400",
    route: "/dashboard/reports/payments",
  },
  {
    id: "committees",
    title: "Committee Report",
    description: "View committee members and positions.",
    icon: UserRoundCog,
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-400",
    route: "/dashboard/reports/committees",
  },
  {
    id: "gallery",
    title: "Gallery Report",
    description: "Analyze albums, images and media activity.",
    icon: Images,
    iconBg: "bg-pink-500/10",
    iconColor: "text-pink-400",
    route: "/dashboard/reports/gallery",
  },
  {
    id: "activity",
    title: "Activity Report",
    description: "Track important admin and system activities.",
    icon: Activity,
    iconBg: "bg-orange-500/10",
    iconColor: "text-orange-400",
    route: "/dashboard/reports/activity",
  },
];