// src/constants/users.js

import adminImage from "../assets/icon/logo.png"
import userImage from "../assets/icon/user.png"
import modaratorImage from "../assets/icon/modarator.png"

export const users = [
    {
        id: 1,
        name: "Alumni Admin",
        email: "admin@alumni.com",
        role: "admin",
        batch: null,
        mobile: "0123456789",
        status: "active",
        avatar: adminImage,
    },
    {
        id: 2,
        name: "Alumni User",
        email: "user@alumni.com",
        role: "user",
        batch: null,
        mobile: "0123456790",
        status: "active",
        avatar: userImage,
    },
    {
        id: 3,
        name: "Alumni Modarator",
        email: "modarator@alumni.com",
        role: "modarator",
        batch: null,
        mobile: "0123456791",
        status: "active",
        avatar: modaratorImage,
    },
    {
        id: 4,
        name: "Nusrat Jahan",
        email: "nusrat.jahan@alumni.com",
        role: "user",
        batch: "2017",
        mobile: "0123456792",
        status: "active",
    },
    {
        id: 5,
        name: "Tanvir Hasan",
        email: "tanvir.hasan@alumni.com",
        role: "user",
        batch: "2019",
        mobile: "0123456793",
        status: "inactive",
    },
    {
        id: 6,
        name: "Sadia Afrin",
        email: "sadia.afrin@alumni.com",
        role: "user",
        batch: "2020",
        mobile: "0123456794",
        status: "active",
    },
    {
        id: 7,
        name: "Fahim Rahman",
        email: "fahim.rahman@alumni.com",
        role: "user",
        batch: "2016",
        mobile: "0123456795",
        status: "active",
    },
    {
        id: 8,
        name: "Jannatul Ferdous",
        email: "jannatul.ferdous@alumni.com",
        role: "user",
        batch: "2021",
        mobile: "0123456796",
        status: "pending",
    },
    {
        id: 9,
        name: "Sakib Khan",
        email: "sakib.khan@alumni.com",
        role: "user",
        batch: "2014",
        mobile: "0123456797",
        status: "active",
    },
    {
        id: 10,
        name: "Mim Akter",
        email: "mim.akter@alumni.com",
        role: "user",
        batch: "2022",
        mobile: "0123456798",
        status: "active",
    },
    {
        id: 11,
        name: "Arif Hossain",
        email: "arif.hossain@alumni.com",
        role: "user",
        batch: "2013",
        mobile: "0123456799",
        status: "inactive",
    },
    {
        id: 12,
        name: "Sumaiya Islam",
        email: "sumaiya.islam@alumni.com",
        role: "user",
        batch: "2019",
        mobile: "0123456800",
        status: "active",
    },
    {
        id: 13,
        name: "Mehedi Hasan",
        email: "mehedi.hasan@alumni.com",
        role: "user",
        batch: "2018",
        mobile: "0123456801",
        status: "active",
    },
    {
        id: 14,
        name: "Tanjim Ahmed",
        email: "tanjim.ahmed@alumni.com",
        role: "user",
        batch: "2020",
        mobile: "0123456802",
        status: "pending",
    },
    {
        id: 15,
        name: "Rafia Sultana",
        email: "rafia.sultana@alumni.com",
        role: "user",
        batch: "2016",
        mobile: "0123456803",
        status: "active",
    },
    {
        id: 16,
        name: "Shakil Ahmed",
        email: "shakil.ahmed@alumni.com",
        role: "user",
        batch: "1989",
        mobile: "0123456804",
        status: "inactive",
    },
    {
        id: 17,
        name: "Farzana Yasmin",
        email: "farzana.yasmin@alumni.com",
        role: "user",
        batch: "2015",
        mobile: "0123456805",
        status: "active",
    },
    {
        id: 18,
        name: "Imran Hossain",
        email: "imran.hossain@alumni.com",
        role: "user",
        batch: "2017",
        mobile: "0123456806",
        status: "active",
    },
    {
        id: 19,
        name: "Mahiya Rahman",
        email: "mahiya.rahman@alumni.com",
        role: "user",
        batch: "2023",
        mobile: "0123456807",
        status: "pending",
    },
    {
        id: 20,
        name: "Nayeem Islam",
        email: "nayeem.islam@alumni.com",
        role: "user",
        batch: "2021",
        mobile: "0123456808",
        status: "active",
    },
    {
        id: 21,
        name: "Sharmin Akter",
        email: "sharmin.akter@alumni.com",
        role: "user",
        batch: "2018",
        mobile: "0123456809",
        status: "inactive",
    },
    {
        id: 22,
        name: "Rashedul Karim",
        email: "rashedul.karim@alumni.com",
        role: "user",
        batch: "2011",
        mobile: "0123456810",
        status: "active",
    },
    {
        id: 23,
        name: "Tasmia Chowdhury",
        email: "tasmia.chowdhury@alumni.com",
        role: "user",
        batch: "2022",
        mobile: "0123456811",
        status: "active",
    },
    {
        id: 24,
        name: "Siam Ahmed",
        email: "siam.ahmed@alumni.com",
        role: "user",
        batch: "2023",
        mobile: "0123456812",
        status: "pending",
    },
    {
        id: 25,
        name: "Lubna Haque",
        email: "lubna.haque@alumni.com",
        role: "user",
        batch: "2019",
        mobile: "0123456813",
        status: "active",
    },
    {
        id: 26,
        name: "Adnan Kabir",
        email: "adnan.kabir@alumni.com",
        role: "user",
        batch: "2014",
        mobile: "0123456814",
        status: "active",
    },
    {
        id: 27,
        name: "Sanjida Islam",
        email: "sanjida.islam@alumni.com",
        role: "user",
        batch: "2020",
        mobile: "0123456815",
        status: "inactive",
    },
    {
        id: 28,
        name: "Mahfuzur Rahman",
        email: "mahfuzur.rahman@alumni.com",
        role: "user",
        batch: "2016",
        mobile: "0123456816",
        status: "active",
    },
    {
        id: 29,
        name: "Anika Tabassum",
        email: "anika.tabassum@alumni.com",
        role: "user",
        batch: "2024",
        mobile: "0123456817",
        status: "pending",
    },
    {
        id: 30,
        name: "Sohel Rana",
        email: "sohel.rana@alumni.com",
        role: "user",
        batch: "2010",
        mobile: "0123456818",
        status: "active",
    },
];